name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          sudo apt install -y libx11-dev
          sudo apt install -y xvfb
          sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sudo export DISPLAY=:99.0

      - name: Test
        run: go test -v ./...
